AY2425S2-CS2113-F12-1/tp

docs/AboutUs.md

Edward Rafael Lukito about us

---

docs/AboutUs.md
src/main/java/fintrek/Command.java
src/main/java/fintrek/FinTrek.java
src/main/java/fintrek/Parser.java
src/main/java/fintrek/misc/DisplayMessage.java

Charly chandra about us

---

src/main/java/fintrek/Command.java
src/main/java/fintrek/FinTrek.java
src/main/java/fintrek/Parser.java
src/main/java/fintrek/misc/DisplayMessage.java

Still need to handle the case when user just key in "/help". Now it will just give an error, I have tried many ways to handle that but failed :(

created a 'HELP' enum to list down all the functions of FinTrek

---

src/test/java/fintrek/ExpenseManagerTest.java

Created test cases for ExpenseManager
1. Filled array list
2. Empty array list
Improve the constant expenses by refactoring them into a helper function

Charly2312 helper function expense manager test

---

src/main/java/fintrek/Expense.java
src/main/java/fintrek/command/Command.java
src/test/java/fintrek/ExpenseManagerTest.java
src/test/java/fintrek/expense/ExpenseTest.java

Fix coding style to follow the coding standard.

Fix coding style to pass CI checks and the coding standard

---

src/test/java/fintrek/ExpenseManagerTest.java

Remove unused import

---

src/main/java/fintrek/FinTrek.java

added logging into FinTrek.java

added logging

---

src/main/java/fintrek/ExpenseManager.java
src/main/java/fintrek/FinTrek.java
src/main/java/fintrek/command/Command.java
src/main/java/fintrek/parser/Parser.java

- Add logging for adding and popping expenses
- Fix bug with delete command in which the correct index was not being deleted
- Move successful parsing logging to parser class

Add logging for adding and popping expenses, fix minor bug with delete command

---

src/main/java/fintrek/ExpenseManager.java
src/main/java/fintrek/command/Command.java

added another assertion in ExpenseManager

added another assertion

---

docs/DeveloperGuide.md

edited some sections:
- user profile 
- value proposition

updated the DG for userprofile and value proposition section

---

docs/DeveloperGuide.md

Input the user stories for v1.0 and v2.0 in the DG

Update user stories in DG

---

src/main/java/fintrek/Expense.java
src/main/java/fintrek/ExpenseManager.java
src/main/java/fintrek/FinTrek.java
src/main/java/fintrek/command/AddRecurringCommand.java
src/main/java/fintrek/command/CommandRegistry.java
src/main/java/fintrek/command/DeleteRecurringCommand.java
src/main/java/fintrek/command/ListRecurringCommand.java
src/main/java/fintrek/misc/MessageDisplayer.java
src/main/java/fintrek/utils/InputValidator.java
src/test/java/fintrek/expense/ExpenseTest.java

Created recurring expenses related functions. 
1. Added AddReccuringCommand.java extending from Command
2. ListRecurringCommand.java to list down all recurring expenses added
3. DeleteRecurringCommand.Java to delete any recurring expense from the list
4. Edited CommandRegistry to include "recurring" to add recurring expense, "delete-recurring" to delete a recurring expense and "list-recurring" to list down all recurring expenses.
5. Edited ExpenseManager to include new functions such as insertRecurringIntoExpenses and checkRecurringExpense().
6. Created a new LocalDate date variable to store recurring expenses date.
I have manually tested them and will create unit tests soon for them. Can make a function to update a date for a general expense (and recurring expense)

Created recurring expenses feature (list, add and delete)

---

src/main/java/fintrek/ExpenseManager.java
src/main/java/fintrek/command/ListCommand.java
src/main/java/fintrek/command/SummaryCommand.java
src/main/java/fintrek/misc/MessageDisplayer.java
src/test/java/fintrek/command/ListCommandTest.java

Update SummaryCommand, remove magic literals, refactor listExpense method

Refactor Code

---

src/main/java/fintrek/command/help/HelpCommand.java
src/test/java/fintrek/expense/ExpenseTest.java

1. Fixed checkstyle error 
2. Fixed a difference from <COMMAND> to [COMMAND]
3. Cleared recurring and general expense list before doing recurring expense test

fixed checkReccuringExpense test case

---

docs/UserGuide.md
docs/team/charly2312.md

1. Edited UG to include recurring expenses related functions
2. Created a new PPP for Charly2312

Edited UG and PPP

---

docs/UserGuide.md
src/main/java/fintrek/FinTrek.java
src/main/java/fintrek/command/add/AddCommand.java
src/main/java/fintrek/command/help/HelpCommand.java
src/main/java/fintrek/command/registry/CommandRegistry.java
src/main/java/fintrek/ui/FinTrekUi.java

- Minor changes to Help Command to sort help descriptions
- Format Add Command description

Refactor FinTrek into Ui and Main

---

docs/UserGuide.md

edit the UG for a minor detail

edit UG for minor fix

---

src/test/java/fintrek/expense/core/ExpenseTest.java
src/test/java/fintrek/util/ExpenseManager.java

1. check that recurring expenses before current date is added to general list
2. check that recurring expenses after current is not added to the general list

Edited test cases to check if recurring expenses due today are added

---

docs/team/edwardrl101.md

Add my PPP

---

src/test/java/fintrek/command/add/AddRecurringCommandTest.java

1. changed hard coded date to creating a newExpense instead for placeholder

fix addRecurring unit test

---

docs/diagrams/sequence/add.puml
docs/diagrams/sequence/delete.puml
docs/diagrams/sequence/edit.puml
docs/diagrams/sequence/list.puml
docs/diagrams/sequence/parser.puml
docs/diagrams/sequence/summary.puml

Extract Parser Logic from command Sequence Diagrams, structure summary sequence diagram accordingly

Update Sequence Diagrams

---

src/main/java/fintrek/expense/service/ExpenseReporter.java
src/main/java/fintrek/parser/CommandRouter.java
src/main/java/fintrek/parser/EditArgumentParser.java
src/main/java/fintrek/parser/FileDataParser.java
src/main/java/fintrek/parser/RouteResult.java
src/test/java/fintrek/expense/service/ExpenseReporterTest.java

1. add more documentation to classes such as EditArgumentParser and FileDataParser
2. Refactor the code in expenseReporter unit tests to follow the format of mapping

add more documentation and edit expenseReporter test to use the new format of mapping

---

docs/DeveloperGuide.md
src/main/java/fintrek/command/add/AddCommand.java

Reverts AY2425S2-CS2113-F12-1/tp#194

Revert "edit DG for '/edit' section and explaining the differences between regular and recurring expenses"

---

docs/DeveloperGuide.md
src/main/java/fintrek/command/add/AddCommand.java

Reverts AY2425S2-CS2113-F12-1/tp#195

Revert "Revert "edit DG for '/edit' section and explaining the differences between regular and recurring expenses""

---

docs/UserGuide.md
src/main/java/fintrek/budget/service/BudgetWarningService.java
src/main/java/fintrek/command/add/AddCommand.java
src/main/java/fintrek/misc/MessageDisplayer.java
src/main/java/fintrek/util/RecurringExpenseProcessor.java

- Refactor code to a new BudgetWarningService class to obey the principle of SRP
- Fix bugs pertaining to new lines printed when budget warnings are not being generated

Refactor code and fix bugs pertaining to budget warnings

---

src/test/java/fintrek/command/add/AddCommandTest.java
src/test/java/fintrek/util/TestUtils.java

1. fix checkstyle error of more than 120 characters
2. remove unused imports

fix CI issue of checkstyle and unused imports

---

src/main/java/fintrek/command/help/HelpCommand.java
src/main/java/fintrek/command/list/ListCommand.java
src/main/java/fintrek/command/summary/AverageCommand.java
src/main/java/fintrek/command/summary/TotalCommand.java
src/test/java/fintrek/command/budget/BudgetLeftCommandTest.java

1. fix indentation 
2. remove unused imports of inputValidator
3. fix helpCommand to not trim and lower case null argument

fix checkstyle issues
